### ISSUE TITLE
App truncates servername

### ISSUE THREAD

**Issue by rcsd5623** [t-markmann/nc-userimporter#1]
When the FQDN in the XML is something like space.rcsd.net the app errors claiming that it failed to make an HTTPS connection to (host='ace.rcsd.ne', port443)

It seems to truncate the first 1 or 2 characters and the last character.  if I change it to  space.rcsd.com,  the error shows the host='ace.rcsd.com'.   

For some reason it does not like names that begin with 'S', 'P', or end with "T'.

**Comment by t-markmann** [comment]
If I enter a FQDN like space.doesnotexist.net in the xml, I get "ace.doesnotexist.ne" in the error message, as you reported.

Right now I don't have a Nextcloud instance running at a .net tld for testing. 
So help me out here please: does this error only occur, if there is **not a real** instance running under that domain, or does it occur even if there is a real Nextcloud running?

**Comment by rcsd5623** [comment]
Thank you for your response.  I realize that my reporting of this issue is not really following appropriate protocol for GitHub and I apologize.

There is an instance of Nextcloud running under the domain, and it is a TLD of .net.  

I have since found a way to use excel to import the users and I certainly do not want to waste any more of your time.

**Comment by t-markmann** [comment]
No problem at all :-) Thank you very much for your bug report. 
I will fix this soon, since there could be others who run into this error.

**Comment by pinpin-xici** [comment]
hi, i have the same problem ,in the config.xml file, my url begin with a 'p' and the script fails ...

**Comment by t-markmann** [comment]
Solved in 30e7968
