### ISSUE TITLE
HTTPSConnectionPool SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by megaherox** [t-markmann/nc-userimporter#10]
When i using nc-userimporter.exe on windows following error came up:

HTTPSConnectionPool(host='censored', port=9443): Max retries exceeded with url: /ocs/v1.php/cloud/groups?search=censored (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

I am using a buyed SSLCert. So its not self singed!

**Comment by t-markmann** [comment]
Do you use an alternative port at your webserver? 9443 is often used, if 443 is used by another service.

The client will use 443 by default for the https connection. Currently we can not set a custom port or deactivate https, we would have to develop that.

**Comment by megaherox** [comment]
Yeah, we use port 9443. Port 443 is used by another service.
 But in the CMD the Error says Port 9443 ? Are you sure that the client will default use 443 when i have in the config.xml following url=YOUR-CLOUD-URL:9443 ?
So without :9443 the Error Message will change to port=443

**Comment by t-markmann** [comment]
I just tried an existing setup on port 7443 and a Letsencrypt cert. This worked well. I can only take guesses about the problem... do you have another Windows system or even a Linux/Mac to test? 

To provide a working package for your situation I uploaded a Windows package here with SSL verification turned off: https://get.edudocs.org/de/assets/nc-userimporter/nc-userimporter_win_no-ssl-verify.zip
You will get a warning that this is not good, but hopefully it works for you.

**Comment by megaherox** [comment]
Thank you for the no SSL Package (: !
I tried with your new Windows Package, now the Error is gone ! But the Script do nothing. I have in the Config a Admin User with a Password that is correct. (without special characters !) 
And also in the Users File Users but on my Nextcloud 17 there a no users... Also i have no Log File.. We have Linux an Windows, so i can test on both.. But Windows is our preferred System.

![next01](https://user-images.githubusercontent.com/30510004/72211924-d258cc00-34d3-11ea-9154-c3d0ee0d9567.PNG)


![next02](https://user-images.githubusercontent.com/30510004/72211935-fcaa8980-34d3-11ea-8ff6-02a4c98bffcc.PNG)

**Comment by t-markmann** [comment]
Nothing happens? So the terminal window just opens and closes right after that?

Try the following: go into your windows shell (press WIN+R, then type "cmd"). Now cd into your nc-userimporter directory and execute nc-userimporter.exe

The shell will remain open even if there are unhandled errors.

**Comment by megaherox** [comment]
![next03](https://user-images.githubusercontent.com/30510004/72219656-cb1fd580-3548-11ea-9375-5cdffb624dac.PNG)

**Comment by t-markmann** [comment]
You found a case we did not test ;-)
Alright, I made a new build, please try: https://get.edudocs.org/de/assets/nc-userimporter/nc-userimporter_win_no-ssl-verify.zip

Here we catch that bug. We have to refactor the whole thing at some time.

**Comment by megaherox** [comment]
Now its working 👍
The User is correctly created and i have a pdf file (:
Thank you for the fast fix.
Will there be a version with SSL on ?

**Comment by t-markmann** [comment]
Great, you're welcome!
SSL is currently always on. Just the verification is turned off in this branch.
