### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by sbellassai** [t-markmann/nc-userimporter#12]
When trying to run the script, I get the following error. I've double and triple checked the config.xml and csv, everything seems to be in order. Any insight?

Copyright (C) 2019-2020 Torsten Markmann (t-markmann), edudocs.org & uplinked.net
Contributors: Johannes Schirge (Shen), Nicolas Stuhlfauth (nicostuhlfauth)
This program comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it under certain conditions.
For details look into LICENSE file (GNU GPLv3).

Traceback (most recent call last):
  File "nc-userimporter.py", line 84, in <module>
  File "<string>", line 1, in <module>
NameError: name 'false' is not defined
[10808] Failed to execute script nc-userimporter

Running on Windows 10 with the provided exe.

**Comment by Shen** [comment]
Did you change <sslverify>True</sslverify> to <sslverify>false</sslverify>?
<sslverify>False</sslverify> should work.

**Comment by Shen** [comment]
No feedback. Seems to be solved.
