### ISSUE TITLE
Problems with python3 and ubuntu

### ISSUE THREAD

**Issue by gitalm** [t-markmann/nc-userimporter#14]
Dear Markmann,

thanks for your good job. I got problem running it on ubuntu with python3.6.
The module qrcode isn't available so i changed minor things to use the module pyqrcode.
First the import
`import pyqrcode as qrcode`
I commented the part of QR-Code class
```
# QR-Code class
#qr = qrcode.QRCode(
#    version=1,
#    error_correction=qrcode.constants.ERROR_CORRECT_L,
#    box_size=10,
#    border=4,
#)
```
and i changed the image creation for the pdf
```
    if response_xmlsoup.find('statuscode').string == "100":
      # generate qr-code
      url = qrcode.create("nc://login/user:" + row[0] + "&password:" + row[2] + "&server:https://" + config_ncUrl)     
      img = url.png(os.path.join( tmp_dir, row[0] + ".png" ), scale=6)
      #qr.clear()
```
and also the new file ending for the image afterwards (*jpg -> *.png)
`      im2 = Image(os.path.join( tmp_dir, row[0] + ".png" ), 200, 200)`

Thanks for your work. 
The whole file is attached.
[nc-userimporter.py.zip](https://github.com/t-markmann/nc-userimporter/files/4473166/nc-userimporter.py.zip)
[nc-userimporter.py.zip](https://github.com/t-markmann/nc-userimporter/files/4473167/nc-userimporter.py.zip)

Best wishes Johannes

**Comment by Shen** [comment]
Thanks for presenting a possible alternative in case there are problems with the QR Code library I used. Maybe I will switch to segno one day (https://pypi.org/project/segno/).
