### ISSUE TITLE
Can't connect on debian VM

### ISSUE THREAD

**Issue by Alexconte31** [t-markmann/nc-userimporter#16]
Hello, 

I would like some help to be able to connect nc-userimporter to my nextcloud on the same VM. I installed nextcloud on a debian 10 VM and try to import users from a csv file.
I saw you script and try it but when i edited the config.xml like this:

    <cloudurl>127.0.0.1/nextcloud</cloudurl> 
    
    <!-- Attention: Please note some special characters are not allowed in passwords, avoid using ) $

i have this error: 

        HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /nextcloud/ocs/v1.php/cloud/groups?search=Lehrkraefte (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1912082cc0>: Failed to establish a new connection: [Errno 111] Connection refused',))
         The CURL request could not be performed.

What can i do to solve that ? 

Well cordially and thank you for your work.

**Comment by Alexconte31** [comment]
hello, 

 I solved my problem by allowing apache to listen on port 443 but still can't import data from csv. I have this error:
      
          [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)
          The CURL request could not be performed.

**Comment by Alexconte31** [comment]
problem solved, i just changed the protocol from https to http in the code ( line 157 )

**Comment by Shen** [comment]
Okay, this seems to be a local problem. Maybe you don't use a secure communication protocol.
