### ISSUE TITLE
Question: self-signed certificate

### ISSUE THREAD

**Issue by Alexconte31** [t-markmann/nc-userimporter#17]
Hello,

Is it possible to add an auto signed certificate to test it on https without having a valid domain name ?

Thank you.

**Comment by t-markmann** [comment]
Have you tried <sslverify>False</sslverify> ?
Then it should work with a self-signed certificate.

**Comment by Alexconte31** [comment]
Hello,
it worked, i put it in the config.xml file. 

Thanks a lot.
