### ISSUE TITLE
nc-userimporter doesn't work anymore

### ISSUE THREAD

**Issue by GrauvoglU** [t-markmann/nc-userimporter#19]
Hello everybody,

to import users into nextclud I tried the nc-userimporter. It worked fine for a day. The next day it stopped working. The following error message (see appendix) appears and the process aborts. I do not know why. I didn't change anything. Maybe someone has a tip for me.

Uli

![Fehler](https://user-images.githubusercontent.com/72066792/94525785-e5175a80-0234-11eb-8439-552cba3744ea.png)

**Comment by t-markmann** [comment]
Do you run it as python script or as built package? Try the build package, it's easier.
Windows, Linux, Mac?

The error occurs when the import preview is generated. Might be a typo in your users.xml. Try to test with a minimal users.xml --> or download the build package completely new.

Hope this helps!
