### ISSUE TITLE
Missing requirements.txt file. for a repeatable installation.

### ISSUE THREAD

**Issue by MaxPeal** [t-markmann/nc-userimporter#20]
Please add a requirements.txt file
for the purpose of achieving a repeatable installation.

**Comment by t-markmann** [comment]
Please have a look at the wiki: 
https://github.com/t-markmann/nc-userimporter/wiki#install-dependencies-for-running-py-script

If there's something missing, look at the imports in the code of nc-userimporter.py : 

import os
import os.path
import sys
import time
import requests
import certifi
import csv
import string
import urllib.parse
import qrcode
import random
import codecs
import html
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from tabulate import tabulate
from bs4 import BeautifulSoup
from datetime import datetime
