### ISSUE TITLE
MAC Download not available

### ISSUE THREAD

**Issue by evoltas** [t-markmann/nc-userimporter#22]
The link  https://get.edudocs.org/de/assets/nc-userimporter/ - leads only to a MS download Zip fiel with an .exe.
Where do I find a MAC Package. Thanks for your help!

**Comment by t-markmann** [comment]
Hi, I currently don't have resources to build the Mac package.

You have several options though:
- use a Windows PC to run the exe
- use a Mac / Linux and run the .py

**Comment by evoltas** [comment]
Hi, thanks for the answer. I have tried to use it on Windows. But it is searching for /users/tm/programs/python37.... It looks like the python package has to be installed first.. 
Is that right or is there a windows package that I can use from your repository?

**Comment by t-markmann** [comment]
That error message is a bit misleading.
In most cases it is caused by a broken config.xml or users.xml

Please check if the files are still in UTF-8.
Apple software creates/changes to other encoding (ANSI). Hope this helps.
