### ISSUE TITLE
Import multiple times: overwrite or duplicate?

### ISSUE THREAD

**Issue by jlgarnier** [t-markmann/nc-userimporter#26]
Hi Community,

I'm preparing a Nextcloud server for a friend (association) and work from home: the server is then connected to my LAN and cannot be used by the members.
I want to import the whole list of members, which I created with all real values, except the passwords but including members' email address. I'd like to import the list to create groups and so on, but DON'T WANT the members to be notified that their account is available. I could just delete all addresses as well: is it enough?

Then, once I returned the server to my friend, I'd like to perform a second import with all email addresses to trigger the email notification "Please connect and change your password": would it overwrite the existing users, as I expect, or would it duplicate the usernames and accounts?

Thanks in advance for your advises!

**Comment by t-markmann** [comment]
Hi!
The seconds run of the script would give you an error message because the users already exist.

I would rather create the users with all data (e-mails and groups) in the first place.
You can surely disable sending e-mails from the server by just disabling/removing the e-mail stack from your Linux server.

Hope this helps.

**Comment by jlgarnier** [comment]
Thanks a lot for this answer! I may disable the email server to prevent pushing message to users, but don't know how I would then reactivate this function once the server is installed in its final location... 🤔 Any clue?

**Comment by t-markmann** [comment]
You can either save those mails and send them later (tricky, look into your linux mail stack) or re-send the invitations Mails (via NC web gui; click on every user to send the mail). 
Or another way: send a mail to your users: "I have created accounts for you. Go there and click on 'Forgot password'"

**Comment by jlgarnier** [comment]
Sorry @t-markmann , missed your last message...

`Or another way: send a mail to your users: "I have created accounts for you. Go there and click on 'Forgot password'"` : by far, the best idea! The KISS principle rules them all! 😁

Thanks again for your help!
