### ISSUE TITLE
UnicodeDecodeError on import

### ISSUE THREAD

**Issue by jlgarnier** [t-markmann/nc-userimporter#28]
Hi all!

I'm trying to use the script locally on the server and set the 'localhost' address in the config.xml. The script breaks on the first line of the CSV file:

```
HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /ocs/v1.php/cloud/groups?search=CDI (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))
The CURL request could not be performed.
```
although I've set <sslverify>False</sslverify>... It seems the script tries to force SSL connection. Can anyone provide a clue on this issue?

Thanks in advance for any help!

**Comment by t-markmann** [comment]
Hi!

You mean this?
<sslverify>True</sslverify> 

This is for SSL verification, not for the SSL connection itself. The script will always use HTTPS for the connection.
In this case, generate a SSL cert for https://localhost and configure your Apache to use that cert.

Hope this helps.

**Comment by jlgarnier** [comment]
Thanks for the answer! I didn't know the script was forcing HTTPS connection. Are you sure Let's Encrypt will deliver a cert for 'localhost'? Anyway, I'll dig the Apache doc to install a valid cert for the test. Thanks again for your support!

**Comment by t-markmann** [comment]
No letsencrypt will not work for localhost. You have to make a self-signed cert.
Good luck :-)
