### ISSUE TITLE
"Invalid Quota Value 1 GB,,,,,,,,,,,,"

### ISSUE THREAD

**Issue by ACemcar** [t-markmann/nc-userimporter#33]
Hi,

I am trying to use this program to mass upload users into my nextcloud server. My only problem is that, occasionally, every single person I try to upload has a bunch of commas behind their Quota value even though I did not put it there. Sometimes this doesn't happen though, and I'm not sure what is causing it.

**Comment by ACemcar** [comment]
Never mind I solved it. Basically, I was trying to add users into multiple groups but I wrote all the information in one cell, and instead of separating the groups by semi-colon i did by a comma. What you need to do is write all the information up to the first group in one cell, then write every new group in its own cell, then put the group admin for and quota value behind the last group in the same cell. Hope this helps anyone who had the same problem as me.

Wrong way: 

User Name;Display Name;Password;Email;Group, Second Group;Group Admin for;Quota

Right Way:

Cell B1(User name;display name;password;email;group) Cell B2 (Second group;Group admin for; quota

**Comment by t-markmann** [comment]
Hi! Would be interesting which Software you used to edit the CSV file. 
To avoid such issues at best have a look at the CSV template with a normal text editor - not with Excel or similar.
But glad you solved it.
