### ISSUE TITLE
The script doesn't run

### ISSUE THREAD

**Issue by bureau2crea** [t-markmann/nc-userimporter#48]
Hi,

I installed Python 3.9 and all required dependencies, and nc-userimport. After, i configured the config file and the CSV File.

But when, i launch the script, it doesn"t work. I have the following lines :

MacBook-Pro-M1:nc-userimporter toto$ ~/Library/Python/3.9/bin/pyinstaller --onefile nc-userimporter.py
115 INFO: PyInstaller: 5.13.0
115 INFO: Python: 3.9.6
124 INFO: Platform: macOS-13.4.1-arm64-arm-64bit
125 INFO: wrote /Users/toto/nc-userimporter/nc-userimporter.spec
127 INFO: Extending PYTHONPATH with paths
['/Users/toto/nc-userimporter']
219 INFO: checking Analysis
230 INFO: checking PYZ
234 INFO: EXE target arch: arm64
234 INFO: Code signing identity: None
235 INFO: checking PKG
236 INFO: Bootloader /Users/toto/Library/Python/3.9/lib/python/site-packages/PyInstaller/bootloader/Darwin-64bit/run
236 INFO: checking EXE
MacBook-Pro-M1:nc-userimporter toto$ 

Can you help me ?

Thanks

**Comment by t-markmann** [comment]
Hi, you don't have to build release packages to run the script. 
Just install the dependencies and run the .py script :-)

I added some lines to the wiki page:
![grafik](https://github.com/t-markmann/nc-userimporter/assets/5323995/3e0257dd-abe5-49fa-ae10-29c90e51004e)

**Comment by bureau2crea** [comment]
Sorry for the incomprehension. I launched the script, but i have the following error :
Traceback (most recent call last):
  File "/Users/toto/nc-userimporter/nc-userimporter.py", line 327, in <module>
    next(readCSV, None)  # skip the headers
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/codecs.py", line 714, in __next__
    return next(self.reader)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/codecs.py", line 645, in __next__
    line = self.readline()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/codecs.py", line 558, in readline
    data = self.read(readsize, firstline=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 0: invalid start byte

I don't know if it's on the CSV file or on another file. Sorry, i'm not a specialist of Python.  Thanks by advance

**Comment by t-markmann** [comment]
I just tested the script with this:
* a minimal users.csv 
![grafik](https://github.com/t-markmann/nc-userimporter/assets/5323995/85630283-7211-4a0c-9ab2-f646fd10078e)
* changed only the necessary in config.xml:
![grafik](https://github.com/t-markmann/nc-userimporter/assets/5323995/c12edde8-2fa7-41e9-b997-5a7ea9815b0e)

It worked fine:
![grafik](https://github.com/t-markmann/nc-userimporter/assets/5323995/6889faed-0d36-494e-87bc-cb270e175d47)

Please provide more details about your config.xml (without passwords or real url) and about your users.csv.
Maybe consider to use a linux PC with python or a Windows PC / VM and the pre-built package (then you don't have to deal with python).

**Comment by bureau2crea** [comment]
Actually, the issue comes from the accents in the first names. Is it possible to handle them or should I remove them?

**Comment by t-markmann** [comment]
Easiest way: remove them. 
The display names can be changed later in the Nextcloud by the users.
