### ISSUE TITLE
Program closes with big database

### ISSUE THREAD

**Issue by Sycotone** [t-markmann/nc-userimporter#49]
I tried out the program with a test user before starting the script with all the users. It worked just fine.
Afterwards I put in all the users data and tried to run the script again. After the first message and hitting ENTER as the [ANY KEY], the window just closes. In a previous issue (https://github.com/t-markmann/nc-userimporter/issues/41)  you commented, that you should run it through a command prompt. The Error code now tells me, that the .csv file does not exist. But if I delete all users except the test user from the .csv file and save it the script runs completely fine again.
Do you have any idea how to fix this?

**Comment by t-markmann** [comment]
How big is the csv file?
Could you send a testfile here (with randomised data), so we can reproduce the error?

In what environment do you run the programm?
OS? From pre-built package or the script itself?

**Comment by Sycotone** [comment]
I found the solution for my problem. I don't know where I read it but someone said he had a problem with the german Umlauten aka ä, ö, ü. So I deleted all of them from the csv and then it worked.

I ran the program from the prebuild package on windows.
