### ISSUE TITLE
[SOLVED] Its possible to import with blank password and without welcome message?

### ISSUE THREAD

**Issue by konfib** [t-markmann/nc-userimporter#50]
Hi,
I could not figure out how to do that:
import without password and without welcome message?
How to configure the "config.xml" file?
If **NO**: an e-mail will be sent. **(is not wanted**)
` <generatepassword>no</generatepassword> <!-- Select yes if you want a password to be generated automatically if no password is specified in user-csv-file. Select no if you want an e-mail to be sent to the user instead with a request to enter a password. In this case a correct e-mail address MUST be entered in the user-csv-file. -->`

If **YES**:  a password will be generated . **(is not wanted**)
` <generatepassword>no</generatepassword> <!-- Select yes if you want a password to be generated automatically if no password is specified in user-csv-file. Select no if you want an e-mail to be sent to the user instead with a request to enter a password. In this case a correct e-mail address MUST be entered in the user-csv-file. -->`

Thanks for answer.

**Comment by t-markmann** [comment]
Hello, that is impossible by design. I think even in the Nextcloud API. 
Reason: somehow the user has to get a password. 
You can't create an account without password.

What are you trying to achieve? Maybe there is a workaround.

Easiest way that is almost like "no password": just fill your .csv file with dummy-passwords.

**Comment by konfib** [comment]
I see, solution would be a .csv file with dummy-passwords.

But manually it is possible by design. 
Under: /settings/users
 it has a checkbox to disable the mail notification for new created users.
And at same time its possible to not set a password.

The purpose is, to create users and manually send them an invitation mail and let them set an own password, by password reset.

**Comment by t-markmann** [comment]
I think we got a misunderstanding here. 
My point was that you can not create a user without password and without mail. 
Re-reading your posts I now understand that you wanted something else and the description in the config.xml might be misleading. 

If you uncheck the "send mail to new users" box in the settings in /settings/user this should be respected in the creation via script/api. 
Could you check that please and report back? I would correct the description then.

**Comment by konfib** [comment]
[SOLVED] Yes you're right!
`my-nc.example.com/index.php/settings/users`
If "send mail to new users"  is unchecked, it's possible to import via csv even without dummy-password and no Welcome Mail is sent. (it was another test Nextcloud, were I forgot this User setting!)

**Comment by skranz0** [comment]
If this is solved, the issue should be closed
